FROM node:14.16-alpine

ENV NODE_ENV=development
WORKDIR "/app"

RUN yarn global add typescript

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

CMD [ "yarn", "run", "server" ]